apiVersion: v1
kind: Service
metadata:
  name: articles-fe-lb
  labels:
    app: fe
    part: articles
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    app: fe
    part: articles
