apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: articles-fe
  labels:
    app: fe
    part: articles
spec:
  selector:
    matchLabels:
      app: fe
      part: articles
  replicas: 2
  template:
    metadata:
      labels:
        app: fe
        part: articles
    spec:
      containers:
        - name: articles-fe
          image: docker.pkg.github.com/mocchi-app/articles-frontend-giftjet/articles-frontend-giftjet:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
