apiVersion: v1
kind: Service
metadata:
  name: brand-be-lb
  labels:
    app: be
    part: brand
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: be
    part: brand
