apiVersion: v1
kind: Service
metadata:
  name: affiliate-fe-lb
  labels:
    app: fe
    part: affiliate
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: fe
    part: affiliate
