kind: PersistentVolume
apiVersion: v1
metadata:
  name: articles-postgres-pv-volume
  labels:
    type: local
    app: postgres
    part: articles
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/articles"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: articles-postgres-pv-claim
  labels:
    app: postgres
    part: articles
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
