apiVersion: v1
kind: Service
metadata:
  name: postgres-articles-strapi-giftjet
  labels:
    app: postgres
    part: articles
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    part: articles
