apiVersion: v1
kind: Service
metadata:
  name: brand-postgres
  labels:
    app: postgres
    part: brand
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    part: brand
