apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-postgres
spec:
  selector:
    matchLabels:
      app: postgres
      part: brand
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        part: brand
    spec:
      containers:
        - name: postgres
          image: postgres:12.3
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: brand-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: brand-postgres-pv-claim
