apiVersion: v1
kind: Service
metadata:
  name: affiliate-postgres
  labels:
    app: postgres
    part: affiliate
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
    part: affiliate
