apiVersion: v1
kind: Service
metadata:
  name: affiliate-be-lb
  labels:
    app: be
    part: affiliate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: be
    part: affiliate
