apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: affiliate-be
  labels:
    app: be
    part: affiliate
spec:
  selector:
    matchLabels:
      app: be
      part: affiliate
  replicas: 2
  template:
    metadata:
      labels:
        app: be
        part: affiliate
    spec:
      containers:
        - name: affiliate-be-kotlin
          image: docker.pkg.github.com/mocchi-app/affiliate-be/affiliate-be:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: affiliate-be-config
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
